# This notebook covers the most fundamental concepts of tensors using Tensorflow

In [50]:
import tensorflow as tf

In [51]:
print(tf.__version__)

2.3.0


## >> create a tensor from tf.constant
- for creating tensors whose values cannot be edited

In [52]:
# creatr a tensor from tf.constant
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [53]:
#check for number of dimentions
scalar.ndim

0

In [54]:
#create a vector
vector = tf.constant([10,10])
print(vector)

tf.Tensor([10 10], shape=(2,), dtype=int32)


In [55]:
#check for number of dimentions
vector.ndim

1

In [56]:
#create a matrix
matrix = tf.constant([[1,3],
                      [4,5],
                      [6,9]])
matrix

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 3],
       [4, 5],
       [6, 9]])>

In [57]:
#check for the number of dimentions
matrix.ndim

2

In [58]:
#create a tensor
tensor = tf.constant([[[1,2,3],
                      [4,5,6]],
                     [[7,8,9],
                      [10,11,12]],
                     [[16,17,18],
                      [19,20,21]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[16, 17, 18],
        [19, 20, 21]]])>

In [59]:
tensor.ndim

3

##### A constant is a single number, a vector is a 1D tensor, a matrix is a 2D tensor while a tensor is an n-dimrntional array

In [60]:
#chaging the tensor datatype
#useful for reducing storage requirenmrent  
a = tf.constant([[1,3],
                [4,5],
                [6,9]], dtype = tf.float16)
a

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[1., 3.],
       [4., 5.],
       [6., 9.]], dtype=float16)>

## >> create a tensor from tf.Variable()
- creates tensors whose values can be edited (like lists in python)

In [61]:
a = tf.Variable([1,3])
a

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([1, 3])>

In [62]:
print(a[0])

tf.Tensor(1, shape=(), dtype=int32)


In [63]:
#changing the tensor value(use assign)
a[0].assign(7)
a

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 3])>

**Note** Rarely will you need to decide between using tf.constant and tf.variable as tf does that for you

## >> creating random tesors

In [64]:
rt1 = tf.random.Generator.from_seed(42)
rt1 = tf.random.uniform(shape=(3,2)) #from random distribution
rt1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.6645621 , 0.44100678],
       [0.3528825 , 0.46448255],
       [0.03366041, 0.68467236]], dtype=float32)>

## >> shuffling tesors

In [122]:
tf.random.set_seed(42) #global level seed 
tf.random.shuffle(rt1, seed = 42 ) #operation level  random seed

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.6645621 , 0.44100678],
       [0.3528825 , 0.46448255],
       [0.03366041, 0.68467236]], dtype=float32)>

> **Rule 4:**  both seeds are required for no change. Seeding is important to ensure a consistent/reproducable experiments

## >> other ways to create tensors

In [125]:
# a tesor of ones
tf.ones(shape=[3, 4], dtype=tf.int16)

<tf.Tensor: shape=(3, 4), dtype=int16, numpy=
array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int16)>

In [126]:
# a tesor of ones
tf.zeros(shape=[3, 4], dtype=tf.int16)

<tf.Tensor: shape=(3, 4), dtype=int16, numpy=
array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int16)>

In [132]:
# from numpy array
import numpy as np 
np_array = np.arange(1,25)
print(np_array)

tf_array = tf.constant(np_array,shape=(2,3,4)) # shape should relate to the number of elements in the numpy array
print(tf_array)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
tf.Tensor(
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]], shape=(2, 3, 4), dtype=int32)
