# This notebook covers the most fundamental concepts of tensors using Tensorflow

In [2]:
import tensorflow as tf

In [3]:
print(tf.__version__)

2.3.0


## create a tensor from tf.constant

In [7]:
# creatr a tensor from tf.constant
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [8]:
#check for number of dimentions
scalar.ndim

0

In [12]:
#create a vector
vector = tf.constant([10,10])
print(vector)

tf.Tensor([10 10], shape=(2,), dtype=int32)


In [14]:
#check for number of dimentions
vector.ndim

1

In [30]:
#create a matrix
matrix = tf.constant([[1,3],
                      [4,5],
                      [6,9]])
matrix

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 3],
       [4, 5],
       [6, 9]])>

In [31]:
#check for the number of dimentions
matrix.ndim

2

In [34]:
#create a tensor
tensor = tf.constant([[[1,2,3],
                      [4,5,6]],
                     [[7,8,9],
                      [10,11,12]],
                     [[16,17,18],
                      [19,20,21]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[16, 17, 18],
        [19, 20, 21]]])>

In [35]:
tensor.ndim

3

##### A constant is a single number, a vector is a 1D tensor, a matrix is a 2D tensor, while a tensor is an n-dimrntional array