# This notebook covers the most fundamental concepts of tensors using Tensorflow

In [209]:
import tensorflow as tf

In [210]:
print(tf.__version__)

2.3.0


### >>Basic math operations

In [346]:
print(tf.square(4).numpy()) #square
print(tf.sqrt(tf.cast(16, tf.float32)).numpy())#reuires none int
print(tf.math.log(tf.cast(16, tf.float32)).numpy()) #log

16
4.0
2.7725887


## >> create a tensor from tf.constant
- for creating tensors whose values cannot be edited

In [347]:
# creatr a tensor from tf.constant
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [348]:
#check for number of dimentions
scalar.ndim

0

In [213]:
#create a vector
vector = tf.constant([10,10])
print(vector)

tf.Tensor([10 10], shape=(2,), dtype=int32)


In [214]:
#check for number of dimentions
vector.ndim

1

In [215]:
#create a matrix
matrix = tf.constant([[1,3],
                      [4,5],
                      [6,9]])
matrix

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 3],
       [4, 5],
       [6, 9]])>

In [216]:
#check for the number of dimentions
matrix.ndim

2

In [217]:
#create a tensor
tensor = tf.constant([[[1,2,3],
                      [4,5,6]],
                     [[7,8,9],
                      [10,11,12]],
                     [[16,17,18],
                      [19,20,21]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[16, 17, 18],
        [19, 20, 21]]])>

In [218]:
tensor.ndim

3

##### A constant is a single number, a vector is a 1D tensor, a matrix is a 2D tensor while a tensor is an n-dimrntional array

In [219]:
#chaging the tensor datatype
#useful for reducing storage requirenmrent  
a = tf.constant([[1,3],
                [4,5],
                [6,9]], dtype = tf.float16)
a

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[1., 3.],
       [4., 5.],
       [6., 9.]], dtype=float16)>

## >> create a tensor from tf.Variable()
- creates tensors whose values can be edited (like lists in python)

In [220]:
a = tf.Variable([1,3])
a

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([1, 3])>

In [221]:
print(a[0])

tf.Tensor(1, shape=(), dtype=int32)


In [222]:
#changing the tensor value(use assign)
a[0].assign(7)
a

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 3])>

**Note** Rarely will you need to decide between using tf.constant and tf.variable as tf does that for you

## >> creating random tesors

In [223]:
rt1 = tf.random.Generator.from_seed(42)
rt1 = tf.random.uniform(shape=(3,2)) #from random distribution
rt1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.6645621 , 0.44100678],
       [0.3528825 , 0.46448255],
       [0.03366041, 0.68467236]], dtype=float32)>

## >> shuffling tesors

In [224]:
tf.random.set_seed(42) #global level seed 
tf.random.shuffle(rt1, seed = 42 ) #operation level  random seed

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.6645621 , 0.44100678],
       [0.3528825 , 0.46448255],
       [0.03366041, 0.68467236]], dtype=float32)>

> **Rule 4:**  both seeds are required for no change. Seeding is important to ensure a consistent/reproducable experiments

## >> other ways to create tensors

In [225]:
# a tesor of ones
tf.ones(shape=[3, 4], dtype=tf.int16)

<tf.Tensor: shape=(3, 4), dtype=int16, numpy=
array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int16)>

In [226]:
# a tesor of ones
tf.zeros(shape=[3, 4], dtype=tf.int16)

<tf.Tensor: shape=(3, 4), dtype=int16, numpy=
array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int16)>

In [227]:
# from numpy array
import numpy as np 
np_array = np.arange(1,25)
print(np_array,"\n")

tf_array = tf.constant(np_array,shape=(2,3,4)) # shape should relate to the number of elements in the numpy array
print(tf_array)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24] 

tf.Tensor(
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]], shape=(2, 3, 4), dtype=int32)


> **Difference between np arrays and tf tensors** tf tensors can run much faster on a GPU for numerical computing

### >> useful tensor attributes

In [228]:
tx = tf.constant([[[1,2,3],
                      [4,5,6]],
                     [[7,8,9],
                      [10,11,12]],
                     [[16,17,18],
                      [19,20,21]]])

#shape
print(tx.shape)

#size/number of elements
print(tf.size(tx))

#number of dimentions
print(tx.ndim)

(3, 2, 3)
tf.Tensor(18, shape=(), dtype=int32)
3


In [229]:
#prettier
tx = tf.constant([[[1,2,3,1],
                      [4,5,6,2]],
                  
                     [[7,8,9,3],
                      [10,11,12,4]],
                  
                     [[16,17,18,5],
                      [19,20,21,6]]])

#shape
print(tx.shape)

#size/number of elements
print(tf.size(tx).numpy())

#number of dimentions
print(tx.ndim)

(3, 2, 4)
24
3


### >> indexing tensors
- works like python lists

In [230]:
#prettier
tx1 = tf.constant([[[1,2,3,1],
                      [4,5,6,2]],
                  
                     [[7,8,9,3],
                      [10,11,12,4]],
                  
                     [[16,17,18,5],
                      [19,20,21,6]]])

#shape
print(tx.shape)

#size/number of elements
print(tf.size(tx).numpy())

#number of dimentions
print(tx.ndim)

(3, 2, 4)
24
3


In [231]:
#first element of each dimention
tx1[:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[ 1,  2],
        [ 4,  5]],

       [[ 7,  8],
        [10, 11]]])>

In [232]:
# last element of each of the 3 dimentions (should be a list)
tx1[:,-1]

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[ 4,  5,  6,  2],
       [10, 11, 12,  4],
       [19, 20, 21,  6]])>

In [233]:
tx1[:2,:,:2]

<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[ 1,  2],
        [ 4,  5]],

       [[ 7,  8],
        [10, 11]]])>

In [234]:
#expanding axis
tx2 = tx1[..., tf.newaxis]
tx2

<tf.Tensor: shape=(3, 2, 4, 1), dtype=int32, numpy=
array([[[[ 1],
         [ 2],
         [ 3],
         [ 1]],

        [[ 4],
         [ 5],
         [ 6],
         [ 2]]],


       [[[ 7],
         [ 8],
         [ 9],
         [ 3]],

        [[10],
         [11],
         [12],
         [ 4]]],


       [[[16],
         [17],
         [18],
         [ 5]],

        [[19],
         [20],
         [21],
         [ 6]]]])>

In [235]:
#expanding axis alternative
tf.expand_dims(tx1,axis = -1) # new axis will be added at the end of the existiing one

<tf.Tensor: shape=(3, 2, 4, 1), dtype=int32, numpy=
array([[[[ 1],
         [ 2],
         [ 3],
         [ 1]],

        [[ 4],
         [ 5],
         [ 6],
         [ 2]]],


       [[[ 7],
         [ 8],
         [ 9],
         [ 3]],

        [[10],
         [11],
         [12],
         [ 4]]],


       [[[16],
         [17],
         [18],
         [ 5]],

        [[19],
         [20],
         [21],
         [ 6]]]])>

In [236]:
tf.expand_dims(tx1,axis = 2) # new axis will be the  third

<tf.Tensor: shape=(3, 2, 1, 4), dtype=int32, numpy=
array([[[[ 1,  2,  3,  1]],

        [[ 4,  5,  6,  2]]],


       [[[ 7,  8,  9,  3]],

        [[10, 11, 12,  4]]],


       [[[16, 17, 18,  5]],

        [[19, 20, 21,  6]]]])>

### >> tensor operations

In [237]:
tx3 = tf.ones([2,3])
tx3.numpy()

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [238]:
#elementwise operations
print(tx3+2)
print(tf.multiply(tx3,5))#better for faster gpu numerical operations
# the above applies to all the basic math operations and elementwise matrix multiplication

tf.Tensor(
[[3. 3. 3.]
 [3. 3. 3.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[5. 5. 5.]
 [5. 5. 5.]], shape=(2, 3), dtype=float32)


In [255]:
#matix multipliction
a = tf.constant([[1,3],
                      [4,5],
                      [6,9]])
b = tf.constant([[1,3],
                [4,5]])
c = tf.matmul(a,b) # short for tf.linalg.matmul(a,b)
c

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[13, 18],
       [24, 37],
       [42, 63]])>

In [256]:
#using python for matrix multiplication
a@b

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[13, 18],
       [24, 37],
       [42, 63]])>

In [257]:
#multiplication with tf.tensordot()
tf.tensordot(a,b, axes =1)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[13, 18],
       [24, 37],
       [42, 63]])>

In [258]:
#matrix transpose
print(tf.transpose(a))

tf.Tensor(
[[1 4 6]
 [3 5 9]], shape=(2, 3), dtype=int32)


In [259]:
#reshing matrices
#prettier
t3 = tf.constant([[[1,2,3,1],
                      [4,5,6,2]],
                  
                     [[7,8,9,3],
                      [10,11,12,4]],
                  
                     [[16,17,18,5],
                      [19,20,21,6]]])
#tf.size(t3)
t4 = tf.reshape(t3,shape = (3,8))
t4

<tf.Tensor: shape=(3, 8), dtype=int32, numpy=
array([[ 1,  2,  3,  1,  4,  5,  6,  2],
       [ 7,  8,  9,  3, 10, 11, 12,  4],
       [16, 17, 18,  5, 19, 20, 21,  6]])>

### >> changing tensor datatype
- use tf.cast()
- save space
- train faster
- mixed precision, keep certain parts of the model 32-bit for stability and others 16-bit, the model will have a lower step    time and train equally as well in terms of the evaluation matrices such as accuracy 

In [264]:
t3 = tf.constant([[1,2,3,1],
                      [4,5,6,2]], tf.float16)
t3

<tf.Tensor: shape=(2, 4), dtype=float16, numpy=
array([[1., 2., 3., 1.],
       [4., 5., 6., 2.]], dtype=float16)>

In [266]:
# cast to int16
t4 = tf.cast(t3, dtype = tf.int16)
t4

<tf.Tensor: shape=(2, 4), dtype=int16, numpy=
array([[1, 2, 3, 1],
       [4, 5, 6, 2]], dtype=int16)>

### >> Aggregating tensors
- condensing/reducing a tensor down to a single value
- find min, max, std, variance, absolute value etc

In [281]:
t5 = tf.constant([[-2,4,-1],
                  [6,0,11],
                  [7,3,9]])
t5

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[-2,  4, -1],
       [ 6,  0, 11],
       [ 7,  3,  9]])>

In [282]:
#min
print(tf.reduce_min(t5).numpy())
print(tf.reduce_max(t5).numpy())
print(tf.reduce_sum(t5).numpy())
print(tf.reduce_mean(t5).numpy())
print(tf.reduce_prod(t5).numpy())

-2
11
37
4
0


In [295]:
#variance 
#frist convert to real or complex datatype
tf.math.reduce_variance(tf.cast(t5, tf.float32)).numpy()

18.320988

In [296]:
#standard devaition
#frist convert to real or complex datatype
tf.math.reduce_std(tf.cast(t5, tf.float32)).numpy()

4.2803025

### >> positional maximum and minmum
- finding the index of the maximum and minimum
- us tf.argmax() and tf.argmin()


In [305]:
t6 = tf.constant([[-2,4,-1],
                  [6,0,11],
                  [7,3,9]])
print(tf.argmax(t6[0]).numpy())#index for max item of the first item of t6
print(tf.argmax(t6).numpy())#index for max item columnwise
print(tf.argmax(t6, axis = 1).numpy())#index for max item rowise
print(tf.argmax(t6[-1]).numpy())#index for max item of the last item of t6

1
[2 0 1]
[1 2 2]
2


### >> Squeezing tensors
- Removing dimensions of size 1 from the shape of a tensor

In [318]:
t7 = tf.constant([[-2],[4],[-1]])
t7.numpy()

array([[-2],
       [ 4],
       [-1]])

In [319]:
t7.shape

TensorShape([3, 1])

In [320]:
t8 = tf.squeeze(t7)
t8.numpy()

array([-2,  4, -1])

In [321]:
t8.shape

TensorShape([3])

### >> one hot encoding

In [330]:
some_list = [1,2,3,4]
tf.one_hot(some_list,depth = 5 ) #depth is the number of digits that will represent an item

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]], dtype=float32)>

In [331]:
some_list = [1,2,3,4]
tf.one_hot(some_list, depth = 5 , on_value = "5", off_value = "11" ) # replace the zeros and ones with 5s and 11s

<tf.Tensor: shape=(4, 5), dtype=string, numpy=
array([[b'11', b'5', b'11', b'11', b'11'],
       [b'11', b'11', b'5', b'11', b'11'],
       [b'11', b'11', b'11', b'5', b'11'],
       [b'11', b'11', b'11', b'11', b'5']], dtype=object)>

> **Note** tesforflow is very compatible with numpy
- a tensor can easily be converted to a numpy arraay and vs
- this allows us to take advantage of both tools

In [351]:
t9 = tf.constant(some_list)
t9

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4])>

In [355]:
#tensor to numpy array
na1 = np.array(t9)
print(na1)
print(type(na1))

[1 2 3 4]
<class 'numpy.ndarray'>


In [356]:
#numpy array to tensor
t10 = tf.constant(na1)
t10

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4])>

### >> runon devices (CPUS, GPUS, TPUS)

In [361]:
tf.config.list_physical_devices #list the devices on which tf is running on

<function tensorflow.python.framework.config.list_physical_devices(device_type=None)>

In [362]:
tf.config.list_physical_devices('GPU') ## check where a GPU is part of the devices

[]

> **NOTE** when a cuda enable GPU is available, tf will automatically use it whenever possible